### ISSUE TITLE
Design and implement the orders model

### ISSUE THREAD

**Issue by rutvik2151** [NYU-Devops-2020-Orders-Team/orders#10]
**As an** Developer
**I need** to create an orders model  
**So that** different application services can interact with the underlying model

**Description:**
We need to design the following - 
* The order model (columns)
* Persistence for the model (PostgreSQL)
* Serialization from model to JSON
* Deserialization from JSON to model

**Assumptions:** 
* The model class will be added in ```model.py```

**Acceptance Criteria:**
```
Given different requirements for the service
When the team discusses the functionality and approves the model
Then the model must define the methods, data attributes, persistence, query methods, and conversion for transmission.
```

**Comment by shivkhattar** [comment]
Model:

- Order: id, customer_id, created_date
- OrderItem: item_id, product, quantity, price, status, order_id

Each Order can have multiple items.
