### ISSUE TITLE
Setup a skeleton Flask project

### ISSUE THREAD

**Issue by shivkhattar** [NYU-Devops-2020-Orders-Team/orders#11]
**As a** Developer
**I need** a skeleton Flask code
**So that** I can add features and enhancements to it

**Assumptions:** 
* We will be using Python with Flask
* This only needs the root API which returns ```Hello from Flask```
* We will add test cases to test the API

**Acceptance Criteria:**
Given that I have the latest application code
When I run ```FLASK_APP=service:app flask run -h 0.0.0.0```
Then I should have the flask server running on ```0.0.0.0:5000```
And When I hit ```0.0.0.0:5000``` I should get ```Hello from Flask```

**Comment by xiaoshi22** [comment]
> **As a** Developer
> **I need** a skeleton Flask code
> **So that** I can add features and enhancements to it
> 
> **Assumptions:**
> 
> * We will be using Python with Flask
> * This only needs the root API which returns `Hello from Flask`
> * We will add test cases to test the API
> 
> **Acceptance Criteria:**
> Given that I have the latest application code
> When I run `flask app.py -h 0.0.0.0`
> Then I should have the flask server running on `0.0.0.0:5000`
> And When I hit `0.0.0.0:5000` I should get `Hello from Flask`
