### ISSUE TITLE
Deliver an order item

### ISSUE THREAD

**Issue by xiaoshi22** [NYU-Devops-2020-Orders-Team/orders#37]
**As a** User
**I need** a way to deliver an order item
**So that** I can deliver an order item

**Assumptions:** 
* The order item exists
* The order item is not canceled yet
* The order item is shipped already

**Additional comments:** 
* Add validations to check the data is complete and valid
* Make sure the entry gets persisted in the table
* Add test cases to test both the success and failure path

**Acceptance Criteria:**

Given the order, `orderID` exists
And I call ```PUT /orders/orderID/items/itemID/deliver```
Then return 200 OK

Given the order, `orderID` or `itemID` do not exist, the order item is canceled/delivered, or the order item is not shipped
And I call ```PUT /orders/orderID/items/itemID/deliver```
Then return 400 BAD REQUEST

**Comment by YufeiGao6** [comment]
If the order item is delivered, we should get 200 OK
