### ISSUE TITLE
Create an order

### ISSUE THREAD

**Issue by rutvik2151** [NYU-Devops-2020-Orders-Team/orders#6]
**As a** User
**I need** to create an order 
**So that**  it shows up in the orders collection

**Assumptions:** 
* A new order is created with a unique order ID
* An order is associated with a customer ID
* An order can have multiple items in it

**Additional comments:** 
* Add validations to check the data is complete and valid
* Make sure the entry gets persisted in the table
* Add test cases to test both the success and failure path

**Acceptance Criteria:**
```
Given a list of items `I` and a customer `c`
When I issue `POST /orders` with the request JSON
Then a new order should be added to the orders collection and the request returns the order-id generated for the order with 201 CREATED.
And when I issue `GET /orders`
Then I should see `{order-id}` in the list of orders

If any information is missing while creating the entry, we should return 400 BAD REQUEST.
```

**Comment by shivkhattar** [comment]
Design for the Request JSON depends on the order model.
